import type { Lang } from "./catalog";

/** Textes d'interface (hors contenu produit) — FR par défaut, AR au toggle. */
export const UI = {
  fr: {
    dir: "ltr" as const,
    switchLabel: "العربية",
    brand: "Maison d'Or",
    ticker: [
      "📞 WHATSAPP : 0722-474350",
      "🚚 LIVRAISON GRATUITE PARTOUT AU MAROC",
      "💵 PAIEMENT À LA LIVRAISON",
      "✅ SERVICE CLIENT 7J/7",
      "🎁 COFFRET CADEAU OFFERT",
    ],
    home: "Accueil",
    reviews: "avis",
    save: "Économisez",
    saved: "économisés",
    bundleTitle: "GROUPEZ & ÉCONOMISEZ",
    piece: (n: number) => (n === 1 ? "1 Pièce" : `${n} Pièces`),
    perPiece: (p: number) => `${p} dh / pièce`,
    cta: "Commander maintenant",
    ctaShort: "Commander",
    color: "Couleur",
    model: "Modèle",
    deliveryBetween: (a: string, b: string) => `Livraison entre ${a} et ${b}`,
    lowStock: (n: number) => `Plus que ${n} pièces en stock — commandez vite !`,
    offerEndsIn: "Offre réservée pendant",
    freeShip: "Livraison gratuite",
    cod: "Paiement à la livraison",
    codDesc: "Vous payez au livreur",
    openBox: "Colis ouvrable",
    openBoxDesc: "Vérifiez avant de payer",
    support: "Service 7j/7",
    supportDesc: "WhatsApp & téléphone",
    saleEnds: "L'offre se termine à minuit",
    qualityTitle: "Qualité & matériaux",
    payDeliveryTitle: "Paiement & livraison",
    payDelivery: [
      "Paiement à la livraison, en espèces au livreur",
      "Livraison gratuite partout au Maroc, sans minimum",
      "Expédition sous 24h, réception en 24h à 72h",
      "Colis ouvrable : vous vérifiez avant de payer",
    ],
    marquee: [
      "LIVRAISON GRATUITE PARTOUT AU MAROC",
      "PAIEMENT À LA LIVRAISON",
      "COFFRET CADEAU OFFERT",
      "SATISFACTION GARANTIE",
    ],
    of: "sur",
    whyTitle: "Pourquoi cette pièce",
    galleryTitle: "Le produit en images",
    available: "au choix",
    includedTitle: "Ce que vous recevez",
    compareTitle: "Maison d'Or vs bijou de marché",
    compareUs: "Maison d'Or",
    compareThem: "Bijou fantaisie classique",
    compareRows: [
      ["Tient dans le temps", "Acier inoxydable de qualité", "Laiton doré qui s'oxyde"],
      ["Eau & parfum", "Aucun risque", "Ternit en quelques semaines"],
      ["Peaux sensibles", "Sans nickel, hypoallergénique", "Rougeurs fréquentes"],
      ["Sertissage", "Pierre par pierre", "Cristaux collés"],
      ["Emballage", "Coffret cadeau offert", "Sachet plastique"],
      ["Avant de payer", "Colis ouvrable au livreur", "Payé d'avance"],
    ],
    specsTitle: "Fiche produit",
    reviewsTitle: "Ce qu'en disent nos clientes",
    verified: "Achat vérifié",
    basedOn: (n: number) => `basé sur ${n} avis`,
    faqTitle: "Questions fréquentes",
    formTitle: "Finalisez votre commande",
    formSub: "Remplissez le formulaire, nous vous appelons pour confirmer avant expédition.",
    fName: "Nom complet",
    fPhone: "Téléphone (WhatsApp)",
    fCity: "Ville",
    fCityPick: "Cherchez votre ville…",
    fAddress: "Adresse de livraison",
    noCity: "Aucune ville trouvée",
    yourOrder: "Votre commande",
    subtotal: "Sous-total",
    discount: "Remise pack",
    shipping: "Livraison",
    free: "Gratuite",
    total: "Total à payer à la livraison",
    submit: "Confirmer ma commande",
    sending: "Enregistrement en cours…",
    orWhats: "Ou commandez sur WhatsApp",
    errName: "Entrez votre nom complet",
    errPhone: "Numéro invalide (ex : 0612345678)",
    errCity: "Choisissez votre ville",
    errAddress: "Entrez votre adresse",
    errGeneric: "Une erreur est survenue, réessayez ou contactez-nous sur WhatsApp.",
    doneTitle: "Commande confirmée !",
    doneMsg: (n: string) =>
      `Votre référence est ${n}. Nous vous appelons dans les prochaines heures pour confirmer la livraison.`,
    doneWhats: "Nous écrire sur WhatsApp",
    upsellBadge: "Offre valable uniquement maintenant",
    upsellTitle: "Ajoutez-la à la même livraison",
    upsellDesc: "50% de réduction — nous l'ajoutons au même colis, sans frais supplémentaires.",
    upsellAdd: "Ajouter à ma commande",
    upsellNo: "Non merci",
    upsellAdded: "Ajouté à votre commande !",
    upsellAddedMsg: "Les deux pièces arriveront dans le même colis.",
    instead: "au lieu de",
    guaranteeTitle: "Commandez sans risque",
    guarantee: [
      ["📦", "Vous ouvrez le colis devant le livreur"],
      ["💵", "Vous ne payez qu'après avoir vu la pièce"],
      ["🔄", "Vous refusez sur place si ça ne vous plaît pas"],
    ],
    days: ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
    months: ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
    dh: "dh",
    viewing: (n: number) => `${n} personnes consultent cette page`,
  },
  ar: {
    dir: "rtl" as const,
    switchLabel: "Français",
    brand: "Maison d'Or",
    ticker: [
      "📞 واتساب : 0722-474350",
      "🚚 توصيل مجاني لكامل المغرب",
      "💵 الخلاص عند الاستلام",
      "✅ خدمة الزبناء 7 أيام/7",
      "🎁 علبة هدية مجانية",
    ],
    home: "الرئيسية",
    reviews: "تقييم",
    save: "توفري",
    saved: "متوفرين",
    bundleTitle: "خدي أكثر ووفري",
    piece: (n: number) => (n === 1 ? "قطعة وحدة" : `${n} قطع`),
    perPiece: (p: number) => `${p} درهم / القطعة`,
    cta: "اطلبي الآن",
    ctaShort: "اطلبي",
    color: "اللون",
    model: "الموديل",
    deliveryBetween: (a: string, b: string) => `التوصيل ما بين ${a} و ${b}`,
    lowStock: (n: number) => `ما بقاو غير ${n} قطع فالستوك — زربي!`,
    offerEndsIn: "العرض محجوز ليك مدة",
    freeShip: "توصيل مجاني",
    cod: "الخلاص عند الاستلام",
    codDesc: "كتخلصي للموصّل",
    openBox: "تقدري تحلي الطرد",
    openBoxDesc: "شوفي قبل ما تخلصي",
    support: "خدمة 7/7",
    supportDesc: "واتساب وتيليفون",
    saleEnds: "العرض كيسالي فنص الليل",
    qualityTitle: "الجودة والمواد",
    payDeliveryTitle: "الخلاص والتوصيل",
    payDelivery: [
      "الخلاص عند الاستلام، نقدًا للموصّل",
      "توصيل مجاني لكامل المغرب، بلا حد أدنى",
      "الإرسال ف24 ساعة، والتوصيل من 24 ل 72 ساعة",
      "تقدري تحلي الطرد وتشوفي قبل ما تخلصي",
    ],
    marquee: [
      "توصيل مجاني لكامل المغرب",
      "الخلاص عند الاستلام",
      "علبة هدية مجانية",
      "الرضا مضمون",
    ],
    of: "من",
    whyTitle: "علاش هاد القطعة",
    galleryTitle: "المنتج بالصور",
    available: "على اختيارك",
    includedTitle: "شنو غادي يوصلك",
    compareTitle: "Maison d'Or مقابل بيجو ديال السوق",
    compareUs: "Maison d'Or",
    compareThem: "بيجو عادي",
    compareRows: [
      ["الصمود مع الوقت", "فولاذ مقاوم للصدأ", "نحاس كيتأكسد"],
      ["الماء والعطر", "بلا خطر", "كيسود ف شي أسابيع"],
      ["البشرة الحساسة", "بدون نيكل", "كيسبب الاحمرار"],
      ["الترصيع", "حجرة بحجرة", "كريستال ملصوق"],
      ["التغليف", "علبة هدية مجانية", "ساشي بلاستيك"],
      ["قبل الخلاص", "تقدري تحلي الطرد", "كتخلصي قبل"],
    ],
    specsTitle: "بطاقة المنتج",
    reviewsTitle: "شنو كيقولو الزبونات",
    verified: "شراء موثق",
    basedOn: (n: number) => `على أساس ${n} تقييم`,
    faqTitle: "أسئلة متكررة",
    formTitle: "كملي الطلب ديالك",
    formSub: "عمري الفورم، وغادي نعيطو ليك باش نأكدو قبل الإرسال.",
    fName: "الاسم الكامل",
    fPhone: "رقم الهاتف (واتساب)",
    fCity: "المدينة",
    fCityPick: "قلبي على المدينة ديالك…",
    fAddress: "عنوان التوصيل",
    noCity: "ما لقيناش هاد المدينة",
    yourOrder: "الطلب ديالك",
    subtotal: "المجموع الفرعي",
    discount: "تخفيض الباك",
    shipping: "التوصيل",
    free: "مجاني",
    total: "المجموع اللي غادي تخلصي عند الاستلام",
    submit: "أكدي الطلب",
    sending: "كنسجلو الطلب…",
    orWhats: "ولا اطلبي عبر واتساب",
    errName: "دخلي الاسم الكامل",
    errPhone: "الرقم ماشي صحيح (مثال: 0612345678)",
    errCity: "ختاري المدينة",
    errAddress: "دخلي العنوان",
    errGeneric: "وقع شي مشكل، عاودي حاولي ولا تواصلي معانا فواتساب.",
    doneTitle: "الطلب تأكد!",
    doneMsg: (n: string) => `المرجع ديالك هو ${n}. غادي نعيطو ليك فالساعات الجاية باش نأكدو التوصيل.`,
    doneWhats: "تواصلي معانا فواتساب",
    upsellBadge: "عرض صالح غير دابا",
    upsellTitle: "زيديها لنفس التوصيل",
    upsellDesc: "تخفيض 50% — غادي نزيدوها فنفس الطرد، بلا زيادة فالتوصيل.",
    upsellAdd: "زيديها للطلب",
    upsellNo: "لا شكرًا",
    upsellAdded: "تزادت للطلب ديالك!",
    upsellAddedMsg: "الجوج قطع غادي يوصلو فنفس الطرد.",
    instead: "عوض",
    guaranteeTitle: "اطلبي بلا خطر",
    guarantee: [
      ["📦", "كتحلي الطرد قدام الموصّل"],
      ["💵", "ما كتخلصي حتى تشوفي القطعة"],
      ["🔄", "ترجعيها فبلاصتها إلى ما عجباتكش"],
    ],
    days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
    months: ["يناير", "فبراير", "مارس", "أبريل", "ماي", "يونيو", "يوليوز", "غشت", "شتنبر", "أكتوبر", "نونبر", "دجنبر"],
    dh: "درهم",
    viewing: (n: number) => `${n} أشخاص كيتصفحو هاد الصفحة`,
  },
};

export type UICopy = (typeof UI)[Lang];
